[workspace]
authors = ["Mr-Leshiy <leshiy12345678@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
name = "mojo-crypto"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
fmt    = "mojo format ."

test   = """
mojo run -I . tests/aes/test_aes.mojo
"""

bench  = """
mojo run -O3 -I . benchmarks/aes/bench_aes.mojo
"""

[dependencies]
mojo = ">=1.0.0b1,<2"
