name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true
      - run: pixi run fmt
      - name: Check for changes
        run: git diff --exit-code
      - run: pixi run test

